name: quizard
description: quiz and flash card app using remote frirebase database

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.11
  flip_card: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^1.0.0


flutter:




  uses-material-design: true































